### Import

In [1]:
import pandas as pd
import datetime as dt

pd.options.display.max_rows = 1000
pd.options.display.max_colwidth = 10000
pd.set_option('display.max_columns', 500)

### General parameters

In [2]:
mimiciii = "PATH TO DATA/mimic-iii(1.4)/"

### Patients

In [3]:
patients = pd.read_csv(mimiciii + "PATIENTS.csv")

In [4]:
patients.head(3)

In [5]:
print("# all patients = ", patients.SUBJECT_ID.nunique())
print("# all patients dead in hosp = ", patients[patients.DOD_HOSP.notnull()].shape[0])
print("# all patients dead after hosp = ", patients[patients.DOD.notnull()].shape[0])
print("# all patients dead = ", patients[patients.EXPIRE_FLAG == 1].shape[0])
print(patients.GENDER.unique())

# all patients =  46520
# all patients dead in hosp =  9974
# all patients dead after hosp =  15759
# all patients dead =  15759
['F' 'M']

### Admission

In [4]:
admissions = pd.read_csv(mimiciii + "ADMISSIONS.csv")

In [5]:
admissions.head(3)

In [6]:
print("# unique patients = ", admissions.SUBJECT_ID.nunique())
print("# hospital admissions = ", admissions.HADM_ID.nunique())
print("# dead at hospital discharge= ", admissions[admissions.HOSPITAL_EXPIRE_FLAG == 1].shape[0])
print("# alive at hospital discharge = ", admissions[admissions.HOSPITAL_EXPIRE_FLAG == 0].shape[0])

# unique patients =  46520
# hospital admissions =  58976
# dead at hospital discharge=  5854
# alive at hospital discharge =  53122

### ICU Stays

In [101]:
icustays = pd.read_csv(mimiciii + "ICUSTAYS.csv")

In [27]:
icustays.head(3)

In [30]:
print("# unique patients = ", icustays.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", icustays.HADM_ID.nunique())
print("# unique icu admissions = ", icustays.ICUSTAY_ID.nunique())
print("# unique icu transfered stays = ", icustays[icustays.FIRST_CAREUNIT != icustays.LAST_CAREUNIT].ICUSTAY_ID.nunique())

# unique patients =  46476
# unique hospital admissions =  57786
# unique icu admissions =  61532
# unique icu transfered stays =  3833

### Transfer

In [7]:
transfers = pd.read_csv(mimiciii + "TRANSFERS.csv")

In [8]:
transfers.head(3)

In [33]:
print("# all patients = ", transfers.SUBJECT_ID.nunique())
print("# all admissions to hospital = ", transfers.HADM_ID.nunique())
print("# all transfers = ", transfers.ROW_ID.nunique())

# all patients =  46520
# all admissions to hospital =  58976
# all transfers =  261897

### Diagnoses ICD

In [15]:
diagnose_icd = pd.read_csv(mimiciii + "DIAGNOSES_ICD.csv")

In [16]:
diagnose_icd.head(3)

In [40]:
print("# all patients = ", diagnose_icd.SUBJECT_ID.nunique())
print("# all hospital admissions = ", diagnose_icd.HADM_ID.nunique())

# all patients =  46520
# all hospital admissions =  58976

In [10]:
d_diagnose_icd = pd.read_csv(mimiciii + "D_ICD_DIAGNOSES.csv")

In [11]:
d_diagnose_icd.head(3)

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,174,01166,TB pneumonia-oth test,"Tuberculous pneumonia [any form], tubercle bacilli not found by bacteriological or histological examination, but tuberculosis confirmed by other methods [inoculation of animals]"
1,175,01170,TB pneumothorax-unspec,"Tuberculous pneumothorax, unspecified"
2,176,01171,TB pneumothorax-no exam,"Tuberculous pneumothorax, bacteriological or histological examination not done"

In [12]:
print("# all codes = ", d_diagnose_icd.ICD9_CODE.nunique())

# all codes =  14567

### Procedure ICD

In [29]:
procedure_icd = pd.read_csv(mimiciii + "PROCEDURES_ICD.csv")

In [30]:
procedure_icd.head(3)

In [31]:
print("# all patients = ", procedure_icd.SUBJECT_ID.nunique())
print("# all hospital admissions = ", procedure_icd.HADM_ID.nunique())

# all patients =  42214
# all hospital admissions =  52243

In [32]:
d_procedure_icd = pd.read_csv(mimiciii + "D_ICD_PROCEDURES.csv")

In [33]:
d_procedure_icd.head(3)

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,264,851,Canthotomy,Canthotomy
1,265,852,Blepharorrhaphy,Blepharorrhaphy
2,266,859,Adjust lid position NEC,Other adjustment of lid position

In [34]:
print("# all codes = ", d_procedure_icd.ICD9_CODE.nunique())

# all codes =  3809

### Microbiologyevents

In [52]:
microevents = pd.read_csv(mimiciii + "MICROBIOLOGYEVENTS.csv")

In [54]:
microevents.head(3)

In [57]:
print("# all micro test orders = ", microevents.ROW_ID.nunique())
print("# unique patients = ", microevents.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", microevents.HADM_ID.nunique())
print("# unique samples (specimens) = ", microevents.SPEC_ITEMID.nunique())

# all micro test orders =  631726
# unique patients =  39184
# unique hospital admissions =  48740
# unique samples (specimens) =  92

### Prescriptions

In [58]:
prescriptions = pd.read_csv(mimiciii + "PRESCRIPTIONS.csv")

<ipython-input>:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  prescriptions = pd.read_csv(mimiciii + "PRESCRIPTIONS.csv")

In [59]:
prescriptions.head(3)

In [60]:
print("# table size = ", prescriptions.shape)
print("# unique patients = ", prescriptions.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", prescriptions.HADM_ID.nunique())
print("# unique icu admissions = ", prescriptions.ICUSTAY_ID.nunique())
print("# unique medication name = ", prescriptions.DRUG.nunique())
print("# unique Generic Sequence Number (GSN) = ", prescriptions.GSN.nunique())
print("# unique National Drug Code (NDC) = ", prescriptions.NDC.nunique())

# table size =  (4156450, 19)
# unique patients =  39363
# unique hospital admissions =  50216
# unique icu admissions =  52151
# unique medication name =  4525
# unique Generic Sequence Number (GSN) =  4685
# unique National Drug Code (NDC) =  4204

### Labevents

In [9]:
labevents = pd.read_csv(mimiciii + "LABEVENTS.csv")

In [10]:
labevents.head(3)

In [11]:
print("# table size = ", labevents.shape)
print("# unique patients = ", labevents.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", labevents.HADM_ID.nunique())
print("# unique Items = ", labevents.ITEMID.nunique())

# table size =  (27854055, 9)
# unique patients =  46252
# unique hospital admissions =  58151
# unique Items =  726

In [12]:
d_labitems = pd.read_csv(mimiciii + "D_LABITEMS.csv")

In [13]:
d_labitems.head(3)

,ROW_ID,ITEMID,LABEL,FLUID,CATEGORY,LOINC_CODE
0,546,51346,Blasts,Cerebrospinal Fluid (CSF),Hematology,26447-3
1,547,51347,Eosinophils,Cerebrospinal Fluid (CSF),Hematology,26451-5
2,548,51348,"Hematocrit, CSF",Cerebrospinal Fluid (CSF),Hematology,30398-2

In [14]:
print("# unique lab item = ", d_labitems.ITEMID.nunique())
print("# unique lab name = ", d_labitems.LABEL.nunique())
print("# unique lab substance = ", d_labitems.FLUID.nunique())
print("# unique lab category = ", d_labitems.CATEGORY.nunique())

# unique lab item =  753
# unique lab name =  589
# unique lab substance =  16
# unique lab category =  6

### D-items

In [6]:
d_items = pd.read_csv(mimiciii + "D_ITEMS.csv")

In [7]:
d_items.head(3)

,ROW_ID,ITEMID,LABEL,ABBREVIATION,DBSOURCE,LINKSTO,CATEGORY,UNITNAME,PARAM_TYPE,CONCEPTID
0,457,497,Patient controlled analgesia (PCA) [Inject],NaN,carevue,chartevents,NaN,NaN,NaN,NaN
1,458,498,PCA Lockout (Min),NaN,carevue,chartevents,NaN,NaN,NaN,NaN
2,459,499,PCA Medication,NaN,carevue,chartevents,NaN,NaN,NaN,NaN

In [8]:
print("# unique items = ", d_items.ITEMID.nunique())
print("# unique label name = ", d_items.LABEL.nunique())
print("# unique categories = ", d_items.CATEGORY.nunique())
print("links to other tables = ", d_items.LINKSTO.unique())
print("types of itemes = ", d_items.PARAM_TYPE.unique())

# unique items =  12487
# unique label name =  11846
# unique categories =  94
links to other tables =  ['chartevents' 'datetimeevents' 'inputevents_cv' 'outputevents'
 'inputevents_mv' 'procedureevents_mv' 'microbiologyevents']
types of itemes =  [nan 'Solution' 'Checkbox' 'Text' 'Numeric' 'Process' 'Date time'
 'Numeric with tag']

### Chartevents

In [5]:
chartevents = pd.read_csv(mimiciii + "CHARTEVENTS.csv", chunksize=1000)

In [6]:
next(chartevents).head(3)

### Datetimeevents

In [4]:
datetimeevents = pd.read_csv(mimiciii + "DATETIMEEVENTS.csv")

<ipython-input>:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  datetimeevents = pd.read_csv(mimiciii + "DATETIMEEVENTS.csv")

In [5]:
datetimeevents.head(3)

In [75]:
print("# unique patients = ", datetimeevents.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", datetimeevents.HADM_ID.nunique())
print("# unique icu admissions = ", datetimeevents.ICUSTAY_ID.nunique())
print("# unique items = ", datetimeevents.ITEMID.nunique())
print("# unique types = ", datetimeevents.VALUEUOM.unique())

# unique patients =  29185
# unique hospital admissions =  36218
# unique icu admissions =  38632
# unique items =  155
# unique types =  ['Date' 'Date and Time']

### Procedureevents_mv

In [9]:
procedureevents = pd.read_csv(mimiciii + "PROCEDUREEVENTS_MV.csv")

In [25]:
procedureevents.head(3)

In [80]:
print("# unique patients = ", procedureevents.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", procedureevents.HADM_ID.nunique())
print("# unique icu admissions = ", procedureevents.ICUSTAY_ID.nunique())
print("# unique items = ", procedureevents.ITEMID.nunique())
print("# unique procedure events = ", procedureevents.ORDERCATEGORYNAME.nunique())
print("# procedure events = ", procedureevents.ORDERCATEGORYNAME.unique())

# unique patients =  17692
# unique hospital admissions =  21894
# unique icu admissions =  23401
# unique items =  116
# unique procedure events =  12
# procedure events =  ['Procedures' 'Ventilation' 'Invasive Lines' 'Imaging' 'Peripheral Lines'
 'Intubation/Extubation' 'Significant Events' 'Continuous Procedures'
 'Dialysis' 'Peritoneal Dialysis' 'CRRT Filter Change' 'Communication']

### Inputevents_mv

In [81]:
inputevents_mv = pd.read_csv(mimiciii + "INPUTEVENTS_MV.csv")

In [82]:
inputevents_mv.head(3)

In [83]:
print("# unique patients = ", inputevents_mv.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", inputevents_mv.HADM_ID.nunique())
print("# unique icu admissions = ", inputevents_mv.ICUSTAY_ID.nunique())
print("# unique items = ", inputevents_mv.ITEMID.nunique())

# unique patients =  17680
# unique hospital admissions =  21879
# unique icu admissions =  23386
# unique items =  278

### Inputevents_cv

In [84]:
inputevents_cv = pd.read_csv(mimiciii + "INPUTEVENTS_CV.csv")

<ipython-input>:1: DtypeWarning: Columns (7,9,17,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  inputevents_cv = pd.read_csv(mimiciii + "INPUTEVENTS_CV.csv")

In [85]:
inputevents_cv.head(3)

In [86]:
print("# unique patients = ", inputevents_cv.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", inputevents_cv.HADM_ID.nunique())
print("# unique icu admissions = ", inputevents_cv.ICUSTAY_ID.nunique())
print("# unique items = ", inputevents_cv.ITEMID.nunique())

# unique patients =  27124
# unique hospital admissions =  31970
# unique icu admissions =  33799
# unique items =  2938

### Outputevents

In [15]:
outputevents = pd.read_csv(mimiciii + "OUTPUTEVENTS.csv")

In [17]:
outputevents.head(3)

In [18]:
outputevents = pd.merge(outputevents, d_icuitems, on=['ITEMID'], how='left')

In [89]:
print("# unique patients = ", outputevents.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", outputevents.HADM_ID.nunique())
print("# unique icu admissions = ", outputevents.ICUSTAY_ID.nunique())
print("# unique items = ", outputevents.ITEMID.nunique())

# unique patients =  41857
# unique hospital admissions =  52008
# unique icu admissions =  55076
# unique items =  1155

### Note

### Noteevents

In [3]:
note = pd.read_csv(mimiciii + "NOTEEVENTS.csv")

<ipython-input>:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  note = pd.read_csv(mimiciii + "NOTEEVENTS.csv")

In [4]:
note.head(1)

In [105]:
print("# table size = ", note.shape)
print("# unique note = ", note.ROW_ID.nunique())
print("# unique patients = ", note.SUBJECT_ID.nunique())
print("# unique hospital admissions = ", note.HADM_ID.nunique())
print("# note types = ", note.CATEGORY.unique())

# table size =  (2083180, 11)
# unique note =  2083180
# unique patients =  46146
# unique hospital admissions =  58361
# note types =  ['Discharge summary' 'Echo' 'ECG' 'Nursing' 'Physician ' 'Rehab Services'
 'Case Management ' 'Respiratory ' 'Nutrition' 'General' 'Social Work'
 'Pharmacy' 'Consult' 'Radiology' 'Nursing/other']

In [99]:
print(note[note.ROW_ID == 174].TEXT[0])