### Import

In [3]:
import pandas as pd
import datetime as dt

pd.options.display.max_rows = 1000
pd.options.display.max_colwidth = 10000
pd.set_option('display.max_columns', 500)

### General parameters

In [4]:
mimiciv = "PATH TO DATA/mimiciv(2.2)/"

# Hosp

### hosp - patients

dod: out of hospital mortality for MIMIC-IV patients up to one year post-hospital discharge.

In [3]:
patients = pd.read_csv(mimiciv + "hosp/patients.csv")

In [4]:
patients.head(3)

In [5]:
print("# all patients = ", patients.subject_id.nunique())
print("# patients alive after one year = ", patients[patients.dod.isnull()].shape[0])
print("# patients dead after one year = ", patients[patients.dod.notnull()].shape[0])
print("# patients over 89 = ", patients[patients.anchor_age > 89].shape[0])
print(patients.gender.unique())

# all patients =  299712
# patients alive after one year =  270636
# patients dead after one year =  29076
# patients over 89 =  6808
['F' 'M']

### hosp - transfer

In [6]:
transfers = pd.read_csv(mimiciv + "hosp/transfers.csv")

In [7]:
transfers.head(3)

In [8]:
print("# all patients = ", transfers.subject_id.nunique())
print("# all admissions to hospital = ", transfers.hadm_id.nunique())
print("# all transfers = ", transfers.transfer_id.nunique())

# all patients =  299712
# all admissions to hospital =  431231
# all transfers =  1890972

### hosp - admissions

In [9]:
admissions = pd.read_csv(mimiciv + "hosp/admissions.csv")

In [10]:
admissions.head(3)

In [11]:
print("# hospital admissions = ", admissions.hadm_id.nunique())
print("# unique patients = ", admissions.subject_id.nunique())
print("# dead at hospital discharge= ", admissions[admissions.hospital_expire_flag == 1].shape[0])
print("# alive at hospital discharge = ", admissions[admissions.hospital_expire_flag == 0].shape[0])

# hospital admissions =  431231
# unique patients =  180733
# dead at hospital discharge=  8609
# alive at hospital discharge =  422622

### hosp - diagnoses_icd

In [58]:
diagnose_icd = pd.read_csv(mimiciv + "hosp/diagnoses_icd.csv")

In [61]:
diagnose_icd.head(3)

In [72]:
print("# all patients = ", diagnose_icd.subject_id.nunique())
print("# all hospital admissions = ", diagnose_icd.hadm_id.nunique())
print("# unique ICD-9  = ", diagnose_icd[diagnose_icd.icd_version == 9].icd_code.nunique())
print("# unique ICD-10 = ", diagnose_icd[diagnose_icd.icd_version == 10].icd_code.nunique())

# all patients =  180640
# all hospital admissions =  430852
# unique ICD-9  =  9072
# unique ICD-10 =  16757

In [63]:
d_diagnose_icd = pd.read_csv(mimiciv + "hosp/d_icd_diagnoses.csv")

In [65]:
d_diagnose_icd.head(3)

  icd_code  icd_version                             long_title
0     0010            9         Cholera due to vibrio cholerae
1     0011            9  Cholera due to vibrio cholerae el tor
2     0019            9                   Cholera, unspecified

In [73]:
print("# unique ICD-9  = ", d_diagnose_icd[d_diagnose_icd.icd_version == 9].icd_code.nunique())
print("# unique ICD-10 = ", d_diagnose_icd[d_diagnose_icd.icd_version == 10].icd_code.nunique())

# unique ICD-9  =  14666
# unique ICD-10 =  95109

### hosp - procedures_icd

Procedures during the hospital stay can be billed (1) by the hospital or (2) by the provider. 
This table contains only procedures billed by the hospital.

The date of the associated procedures. Date does not strictly correlate with seq_num.

In [6]:
procedure_icd = pd.read_csv(mimiciv + "hosp/procedures_icd.csv")

In [7]:
procedure_icd.head(3)

In [8]:
print("# all patients = ", procedure_icd.subject_id.nunique())
print("# all hospital admissions = ", procedure_icd.hadm_id.nunique())
print("# unique ICD-9  = ", procedure_icd[procedure_icd.icd_version == 9].icd_code.nunique())
print("# unique ICD-10 = ", procedure_icd[procedure_icd.icd_version == 10].icd_code.nunique())

# all patients =  121891
# all hospital admissions =  229445
# unique ICD-9  =  2544
# unique ICD-10 =  10031

In [9]:
d_procedure_icd = pd.read_csv(mimiciv + "hosp/d_icd_procedures.csv")

In [10]:
d_procedure_icd.head(3)

  icd_code  icd_version                                             long_title
0     0001            9     Therapeutic ultrasound of vessels of head and neck
1     0002            9                        Therapeutic ultrasound of heart
2     0003            9  Therapeutic ultrasound of peripheral vascular vessels

In [11]:
print("# unique ICD-9  = ", d_procedure_icd[d_procedure_icd.icd_version == 9].icd_code.nunique())
print("# unique ICD-10 = ", d_procedure_icd[d_procedure_icd.icd_version == 10].icd_code.nunique())

# unique ICD-9  =  3888
# unique ICD-10 =  81369

### hosp - microbiologyevents

In [3]:
microevents = pd.read_csv(mimiciv + "hosp/microbiologyevents.csv")

<ipython-input>:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  microevents = pd.read_csv(mimiciv + "hosp/microbiologyevents.csv")

In [4]:
microevents.head(1)

In [98]:
print("# all micro test orders = ", microevents.microevent_id.nunique())
print("# unique patients = ", microevents.subject_id.nunique())
print("# unique hospital admissions = ", microevents.hadm_id.nunique())
print("# unique samples (specimens) = ", microevents.micro_specimen_id.nunique())
print("# rows with missing hospital admissions = ", microevents[microevents.hadm_id.isnull()].shape[0])

# all micro test orders =  3228713
# unique patients =  181226
# unique hospital admissions =  164140
# unique samples (specimens) =  1587215
# rows with missing hospital admissions =  1830396

### hosp - prescriptions

The prescriptions and pharmacy tables are intended to be used together: prescriptions contains the order made by a provider and pharmacy stores detailed information regarding the compound prescribed.

The eMAR system was deployed between 2014–2016, and thus all hospitalizations from 2016 onward would be anticipated to have records within eMAR.

In [3]:
prescriptions = pd.read_csv(mimiciv + "hosp/prescriptions.csv")

<ipython-input>:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  prescriptions = pd.read_csv(mimiciv + "hosp/prescriptions.csv")

In [4]:
prescriptions.head(3)

In [6]:
print("# table size = ", prescriptions.shape)
print("# unique patients = ", prescriptions.subject_id.nunique())
print("# unique hospital admissions = ", prescriptions.hadm_id.nunique())
print("# unique id to link administrations in emar to pharmacy table = ", prescriptions.pharmacy_id.nunique())
print("# unique medication name = ", prescriptions.drug.nunique())
print("# unique Generic Sequence Number (GSN) = ", prescriptions.gsn.nunique())
print("# unique National Drug Code (NDC) = ", prescriptions.ndc.nunique())

# table size =  (15416708, 21)
# unique patients =  158421
# unique hospital admissions =  365442
# unique id to link administrations in emar to pharmacy table =  13533220
# unique medication name =  9613
# unique Generic Sequence Number (GSN) =  6910
# unique National Drug Code (NDC) =  5733

### hosp - pharmacy

In [12]:
pharmacy = pd.read_csv(mimiciv + "hosp/pharmacy.csv")

<ipython-input>:1: DtypeWarning: Columns (16,18,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  pharmacy = pd.read_csv(mimiciv + "hosp/pharmacy.csv")

In [14]:
pharmacy.head(3)

In [17]:
print("# table size = ", pharmacy.shape)
print("# unique patients = ", pharmacy.subject_id.nunique())
print("# unique hospital admissions = ", pharmacy.hadm_id.nunique())
print("# unique medication name = ", pharmacy.medication.nunique())

# table size =  (13584514, 27)
# unique patients =  158421
# unique hospital admissions =  365442
# unique medication name =  9677

### hosp - labevent

In [13]:
labevents = pd.read_csv(mimiciv + "hosp/labevents.csv")

In [15]:
labevents.head(3)

In [18]:
print("# table size = ", labevents.shape)
print("# unique patients = ", labevents.subject_id.nunique())
print("# unique hospital admissions = ", labevents.hadm_id.nunique())
print("# unique medication name = ", labevents.itemid.nunique())

# table size =  (118171367, 16)
# unique patients =  255876
# unique hospital admissions =  351034
# unique medication name =  915

### hosp - d_labitems

In [8]:
d_labitems = pd.read_csv(mimiciv + "hosp/d_labitems.csv")

In [9]:
d_labitems.head(3)

   itemid                                label  fluid   category
0   50801           Alveolar-arterial Gradient  Blood  Blood Gas
1   50802                          Base Excess  Blood  Blood Gas
2   50803  Calculated Bicarbonate, Whole Blood  Blood  Blood Gas

In [10]:
print("# unique lab item = ", d_labitems.itemid.nunique())
print("# unique lab name = ", d_labitems.label.nunique())
print("# unique lab substance = ", d_labitems.fluid.nunique())
print("# unique lab category = ", d_labitems.category.nunique())

# unique lab item =  1622
# unique lab name =  1170
# unique lab substance =  12
# unique lab category =  3

# ICU

### icu - icustays

In [14]:
icustays = pd.read_csv(mimiciv + "icu/icustays.csv")

In [15]:
icustays.head(3)

In [16]:
print("# unique patients = ", icustays.subject_id.nunique())
print("# unique hospital admissions = ", icustays.hadm_id.nunique())
print("# unique icu admissions = ", icustays.stay_id.nunique())
print("# unique icu transfered stays = ", icustays[icustays.first_careunit != icustays.last_careunit].stay_id.nunique())

# unique patients =  50920
# unique hospital admissions =  66239
# unique icu admissions =  73181
# unique icu transfered stays =  5323

### icu - d_items

In [3]:
d_items = pd.read_csv(mimiciv + "icu/d_items.csv")

In [4]:
d_items.head(3)

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
0,220001,Problem List,Problem List,chartevents,General,NaN,Text,NaN,NaN
1,220003,ICU Admission date,ICU Admission date,datetimeevents,ADT,NaN,Date and time,NaN,NaN
2,220045,Heart Rate,HR,chartevents,Routine Vital Signs,bpm,Numeric,NaN,NaN

In [5]:
print("# unique items = ", d_items.itemid.nunique())
print("# unique label name = ", d_items.label.nunique())
print("# unique categories = ", d_items.category.nunique())
print("links to other tables = ", d_items.linksto.unique())
print("types of itemes = ", d_items.param_type.unique())

# unique items =  4014
# unique label name =  3888
# unique categories =  81
links to other tables =  ['chartevents' 'datetimeevents' 'ingredientevents' 'inputevents'
 'procedureevents' 'outputevents']
types of itemes =  ['Text' 'Date and time' 'Numeric' 'Ingredient' 'Solution' 'Processes'
 'Checkbox' 'Numeric with tag']

### icu - chartevent

In [37]:
chartevents = pd.read_csv(mimiciv + "icu/chartevents.csv", chunksize=100)

In [38]:
next(chartevents).head(3)

### icu - datetimeevents

In [20]:
datetimeevents = pd.read_csv(mimiciv + "icu/datetimeevents.csv")

In [21]:
datetimeevents.head(3)

In [22]:
print("# unique patients = ", datetimeevents.subject_id.nunique())
print("# unique hospital admissions = ", datetimeevents.hadm_id.nunique())
print("# unique icu admissions = ", datetimeevents.stay_id.nunique())
print("# unique items = ", datetimeevents.itemid.nunique())
print("# unique types = ", datetimeevents.valueuom.unique())

# unique patients =  50705
# unique hospital admissions =  65908
# unique icu admissions =  72520
# unique items =  170
# unique types =  ['Date' 'Date and Time']

### icu - procedureevents

This table is not a required documentation field during routine care. As a result, existence of procedures here indicates their presence, but absence does not indicate the procedure was not conducted.

In [23]:
procedureevents = pd.read_csv(mimiciv + "icu/procedureevents.csv")

In [24]:
procedureevents.head(3)

In [25]:
print("# unique patients = ", procedureevents.subject_id.nunique())
print("# unique hospital admissions = ", procedureevents.hadm_id.nunique())
print("# unique icu admissions = ", procedureevents.stay_id.nunique())
print("# unique items = ", procedureevents.itemid.nunique())
print("# unique procedure events = ", procedureevents.ordercategoryname.nunique())
print("# procedure events = ", procedureevents.ordercategoryname.unique())

# unique patients =  50843
# unique hospital admissions =  66127
# unique icu admissions =  72711
# unique items =  157
# unique procedure events =  14
# procedure events =  ['Procedures' 'Peripheral Lines' 'Ventilation' 'Communication' 'Imaging'
 'Invasive Lines' 'Intubation/Extubation' 'Tubes' 'Significant Events'
 'Dialysis' 'Continuous Procedures' 'CRRT Filter Change'
 '17 - Inhaled Meds' 'Peritoneal Dialysis']

### icu - inputevents

In [26]:
inputevents = pd.read_csv(mimiciv + "icu/inputevents.csv")

In [27]:
inputevents.head(3)

In [28]:
print("# unique patients = ", inputevents.subject_id.nunique())
print("# unique hospital admissions = ", inputevents.hadm_id.nunique())
print("# unique icu admissions = ", inputevents.stay_id.nunique())
print("# unique items = ", inputevents.itemid.nunique())

# unique patients =  50755
# unique hospital admissions =  65986
# unique icu admissions =  72690
# unique items =  324

### icu - outputs

In [29]:
outputevents = pd.read_csv(mimiciv + "icu/outputevents.csv")

In [30]:
outputevents.head(3)

In [31]:
print("# unique patients = ", outputevents.subject_id.nunique())
print("# unique hospital admissions = ", outputevents.hadm_id.nunique())
print("# unique icu admissions = ", outputevents.stay_id.nunique())
print("# unique items = ", outputevents.itemid.nunique())

# unique patients =  50198
# unique hospital admissions =  64692
# unique icu admissions =  71111
# unique items =  71

# Note

### note - discharge

In [8]:
discharge_note = pd.read_csv(mimiciv + "note/discharge.csv")

In [12]:
discharge_note.head(1)

In [10]:
print("# table size = ", discharge_note.shape)
print("# unique discharge note = ", discharge_note.note_id.nunique())
print("# unique patients = ", discharge_note.subject_id.nunique())
print("# unique hospital admissions = ", discharge_note.hadm_id.nunique())
print("# discharge types = ", discharge_note.note_type.unique())

# table size =  (331794, 8)
# unique discharge note =  331794
# unique patients =  145915
# unique hospital admissions =  331794
# discharge types =  ['DS']

In [11]:
print(discharge_note[discharge_note.note_id == "10000032-DS-22"].text[1])

### note - radiology

In [3]:
radiology_note = pd.read_csv(mimiciv + "note/radiology.csv")

In [4]:
radiology_note.head(1)

In [13]:
print("# table size = ", radiology_note.shape)
print("# unique radiology note = ", radiology_note.note_id.nunique())
print("# unique patients = ", radiology_note.subject_id.nunique())
print("# unique hospital admissions = ", radiology_note.hadm_id.nunique())
print("# radiology types = ", radiology_note.note_type.unique())

# table size =  (2321355, 8)
# unique radiology note =  2321355
# unique patients =  237427
# unique hospital admissions =  309670
# radiology types =  ['RR' 'AR']

In [6]:
print(radiology_note[radiology_note.note_id == "10000032-RR-14"].text[0])

EXAMINATION:  CHEST (PA AND LAT)

INDICATION:  ___ with new onset ascites  // eval for infection

TECHNIQUE:  Chest PA and lateral

COMPARISON:  None.

FINDINGS:

There is no focal consolidation, pleural effusion or pneumothorax.  Bilateral
nodular opacities that most likely represent nipple shadows. The
cardiomediastinal silhouette is normal.  Clips project over the left lung,
potentially within the breast. The imaged upper abdomen is unremarkable.
Chronic deformity of the posterior left sixth and seventh ribs are noted.

IMPRESSION:

No acute cardiopulmonary process.

### cxr - images

In [30]:
cxrrecord = pd.read_csv(mimiciv + "cxr/cxr-record-list.csv")
cxrmetadata = pd.read_csv(mimiciv + "cxr/mimic-cxr-2.0.0-metadata.csv")

In [31]:
cxr_record = pd.merge(cxrmetadata, cxrrecord, on=['dicom_id', 'subject_id', 'study_id'], how='left')

In [32]:
cxr_record['StudyDate'] = pd.to_datetime(cxr_record['StudyDate'], format='%Y%m%d')
cxr_record['StudyTime'] = cxr_record.apply(lambda x : '%#010.3f' % x['StudyTime'] ,1)
cxr_record['StudyTime'] = pd.to_datetime(cxr_record['StudyTime'], format='%H%M%S.%f').dt.time
cxr_record['cxrtime']   = cxr_record.apply(lambda r : dt.datetime.combine(r['StudyDate'],r['StudyTime']),1)
cxr_record['cxrtime']   = cxr_record['cxrtime'].dt.floor('Min')

In [33]:
cxr_record.head(2)

In [34]:
print("# table size = ", cxrrecord.shape)
print("# unique radiology cxr = ", cxrrecord.dicom_id.nunique())
print("# unique patients = ", cxr_record.subject_id.nunique())
print("# unique study id = ", cxr_record.study_id.nunique())
print("# radiology types = ", cxr_record.PerformedProcedureStepDescription.nunique())

# table size =  (377110, 4)
# unique radiology cxr =  377110
# unique patients =  65379
# unique study id =  227835
# radiology types =  47

### cxr images with lung segmentation

In [35]:
# https://physionet.org/content/chest-x-ray-segmentation/1.0.0/

In [40]:
lung_mask = pd.read_csv(mimiciv + "cxr/lung_segmentation(mimic-cxr-1.0)/CXLSeg-mask.csv")

In [41]:
lung_mask.head(3)

In [42]:
print("# table size = ", lung_mask.shape)
print("# unique radiology cxr = ", lung_mask.dicom_id.nunique())
print("# unique patients = ", lung_mask.subject_id.nunique())
print("# unique study id = ", lung_mask.study_id.nunique())

# table size =  (243324, 4)
# unique radiology cxr =  243324
# unique patients =  63945
# unique study id =  218131

### cxr images labels

In [38]:
cxrchexpert = pd.read_csv(mimiciv + "cxr/mimic-cxr-2.0.0-chexpert.csv")

In [39]:
cxrchexpert.head(2)

In [40]:
print("# table size = ", cxrchexpert.shape)
print("# unique patients = ", cxrchexpert.subject_id.nunique())
print("# unique study id = ", cxrchexpert.study_id.nunique())

# table size =  (227827, 16)
# unique patients =  65379
# unique study id =  227827

### radiology report for cxr images

In [68]:
cxrstudy = pd.read_csv(mimiciv + "cxr/cxr-study-list.csv")

In [69]:
cxrstudy.head(2)

In [70]:
print("# table size = ", cxrstudy.shape)
print("# unique patients = ", cxrstudy.subject_id.nunique())
print("# unique study id = ", cxrstudy.study_id.nunique())

# table size =  (227835, 3)
# unique patients =  65379
# unique study id =  227835

### link of cxr images to their radiology report

In [62]:
cxr_study = cxr_record[['subject_id', 'study_id', 'dicom_id', 'path']]
cxr_study = pd.merge(cxr_study, cxrstudy, on=['subject_id', 'study_id'], how='left')
cxr_study.rename(columns={"path_x": "cxr_img_path", "path_y": "cxr_report_path"}, inplace=True)

In [72]:
cxr_study.head(2)

In [74]:
print("# table size = ", cxr_study.shape)
print("# unique patients = ", cxr_study.subject_id.nunique())
print("# unique study id = ", cxr_study.study_id.nunique())
print("# unique images = ", cxr_study.dicom_id.nunique())

# table size =  (377110, 5)
# unique patients =  65379
# unique study id =  227835
# unique images =  377110

## ECG

In [15]:
ecg = pd.read_csv(mimiciv + "ecg/record_list.csv")

In [20]:
ecg.head(2)

In [21]:
print("# table size = ", ecg.shape)
print("# unique patients = ", ecg.subject_id.nunique())
print("# unique study id = ", ecg.study_id.nunique())
print("# unique ecg = ", ecg.path.nunique())

# table size =  (800035, 5)
# unique patients =  161352
# unique study id =  800035
# unique ecg =  800035

### ECG Machine Measurements

In [24]:
ecg_mm = pd.read_csv(mimiciv + "ecg/machine_measurements.csv", low_memory=False)

In [26]:
ecg_mm.head(2)

In [28]:
print("# table size = ", ecg_mm.shape)
print("# unique patients = ", ecg_mm.subject_id.nunique())
print("# unique study id = ", ecg_mm.study_id.nunique())
print("# unique ecg = ", ecg_mm.cart_id.nunique())

# table size =  (800035, 33)
# unique patients =  161352
# unique study id =  800035
# unique ecg =  156

### ECG Report

In [18]:
ecg_report = pd.read_csv(mimiciv + "ecg/waveform_note_links.csv")

In [19]:
ecg_report.head(2)

In [22]:
print("# table size = ", ecg_report.shape)
print("# unique patients = ", ecg_report.subject_id.nunique())
print("# unique study id = ", ecg_report.study_id.nunique())
print("# unique ecg = ", ecg_report.note_id.nunique())

# table size =  (609272, 6)
# unique patients =  105293
# unique study id =  609265
# unique ecg =  609270